- name: mutt | Установка и конфигурирование mutt
  hosts: nginx
  become: true

  tasks:
    - name: update
      apt:
        update_cache=yes
      tags:
        - update-apt
    - name: mutt | Установка mutt
      apt:
        name: mutt
        state: latest
      tags:
        - mutt-package
    - name: mutt | Копирование конфигурации из шаблона
      template:
        src: conf/.muttrc
        dest: ~/.muttrc
        force: no   # Не меняет конфигурационный файл, если он уже существует
        mode: '0600'
      tags:
        - mutt-configuration
