- name: mutt | Установка и конфигурирование mutt
  hosts: nginx
  become: true

  tasks:
    - name: update
      apt:
        update_cache=yes
    - name: mutt | Установка mutt
      apt:
        name: mutt
        state: latest
